[workspace]
members = []
resolver = "2"

[workspace.package]
authors = ["Joe Caulfield <jcaulfield135@gmail.com>"]
repository = "https://github.com/buffalojoec/invoke"
license = "Apache-2.0"
edition = "2021"

[workspace.dependencies]
